"use client";

import { useEffect, useState } from "react";
import api from "@/lib/axios";
import Link from "next/link";
import { 
  ArrowLeft, 
  Sparkles, 
  Clock, 
  Brain, 
  CheckCircle, 
  Info,
  Zap
} from "lucide-react";

export default function ExercisePage() {
  const [exercises, setExercises] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetchExercises();
  }, []);

  const fetchExercises = async () => {
    try {
      const res = await api.get("/exercises");
      // res.data will be the JSON array from Gemini
      setExercises(res.data);
    } catch (e) {
      console.error("Failed to fetch exercises");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-slate-50 p-6 md:p-12">
      <div className="max-w-5xl mx-auto">
        
        {/* Navigation */}
        <div className="mb-10">
          <Link 
            href="/dashboard" 
            className="flex items-center gap-2 text-slate-500 hover:text-blue-600 transition font-medium"
          >
            <ArrowLeft size={20} /> Back to Dashboard
          </Link>
        </div>

        {/* Header Section */}
        <header className="mb-12 relative">
          <div className="flex items-center gap-3 mb-4">
            <div className="bg-purple-600 p-2 rounded-lg text-white">
              <Brain size={24} />
            </div>
            <span className="text-purple-600 font-bold uppercase tracking-widest text-sm">
              CompanionX Mental Lab
            </span>
          </div>
          <h1 className="text-5xl font-black text-slate-900 mb-4 tracking-tight">
            Your Personal <span className="text-blue-600">Growth Plan</span>
          </h1>
          <p className="text-slate-500 text-lg max-w-2xl leading-relaxed">
            These exercises are generated by our AI based on your onboarding answers 
            and recent mood trends. They update as you grow.
          </p>

          {/* Background Decorative Element */}
          <div className="absolute top-0 right-0 -z-10 opacity-10">
            <Sparkles size={120} className="text-purple-600" />
          </div>
        </header>

        {loading ? (
          <div className="flex flex-col items-center justify-center py-20 bg-white rounded-[3rem] shadow-sm border border-slate-100">
            <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-600 mb-4"></div>
            <p className="text-slate-500 font-medium italic">Gemini is preparing your lab...</p>
          </div>
        ) : exercises.length === 0 ? (
          <div className="bg-white rounded-[3rem] p-16 text-center shadow-sm border border-slate-100">
            <Zap size={48} className="mx-auto text-slate-200 mb-6" />
            <h2 className="text-2xl font-bold text-slate-800 mb-2">No Exercises Ready Yet</h2>
            <p className="text-slate-500 max-w-md mx-auto">
              Please finish your onboarding or add a few mood journal entries to trigger your personalized plan.
            </p>
          </div>
        ) : (
          <div className="grid gap-8">
            {exercises.map((ex: any, idx: number) => (
              <div 
                key={idx} 
                className="bg-white rounded-[2.5rem] p-8 md:p-10 shadow-sm border border-slate-100 hover:shadow-xl hover:border-blue-100 transition-all group"
              >
                <div className="flex flex-wrap justify-between items-start gap-4 mb-6">
                  <div className="flex items-center gap-3">
                    <span className="bg-blue-50 text-blue-600 px-4 py-1.5 rounded-full text-xs font-bold uppercase tracking-widest">
                      {ex.category || "General"}
                    </span>
                    <div className="flex items-center gap-1 text-slate-400 text-sm font-medium">
                      <Clock size={16} /> {ex.duration || "5-10 mins"}
                    </div>
                  </div>
                  
                  {/* Adaptive Badge: Only shows if 'why_now' exists */}
                  {ex.why_now && (
                    <div className="flex items-center gap-1.5 text-emerald-600 bg-emerald-50 px-3 py-1 rounded-lg text-xs font-bold">
                      <Sparkles size={14} className="fill-current" />
                      ADAPTIVE MATCH
                    </div>
                  )}
                </div>

                <h3 className="text-3xl font-bold text-slate-900 mb-4 group-hover:text-blue-600 transition-colors">
                  {ex.title}
                </h3>
                
                <p className="text-slate-600 text-lg leading-relaxed mb-8">
                  {ex.description}
                </p>

                {/* AI Reasoning Section */}
                {ex.why_now && (
                  <div className="bg-slate-50 rounded-2xl p-6 mb-8 border-l-4 border-blue-400 flex gap-4">
                    <div className="text-blue-400 mt-1">
                      <Info size={20} />
                    </div>
                    <div>
                      <h4 className="text-xs font-black text-slate-400 uppercase tracking-widest mb-1">Therapist Notes (AI)</h4>
                      <p className="text-slate-700 italic font-medium">
                        "{ex.why_now}"
                      </p>
                    </div>
                  </div>
                )}

                <div className="flex items-center justify-between">
                  <button className="bg-slate-900 text-white px-8 py-3.5 rounded-2xl font-bold flex items-center gap-2 hover:bg-blue-600 transition-all shadow-lg hover:gap-4">
                    Start Now <CheckCircle size={20} />
                  </button>
                  <span className="text-slate-300 text-sm font-medium hidden sm:block">
                    Recommended for today
                  </span>
                </div>
              </div>
            ))}
          </div>
        )}

        {/* Pro Tip Footer */}
        <div className="mt-16 bg-blue-900 rounded-[2.5rem] p-10 text-white text-center shadow-2xl relative overflow-hidden">
            <div className="relative z-10">
                <h3 className="text-2xl font-bold mb-3">Keep Journaling!</h3>
                <p className="text-blue-100 max-w-xl mx-auto mb-0 leading-relaxed">
                    The more you write in your Mood Journal, the more accurate and helpful 
                    these exercises will become. AI re-analyzes your journey every 5 entries.
                </p>
            </div>
            <div className="absolute top-0 right-0 -mt-10 -mr-10 w-40 h-40 bg-blue-500/20 rounded-full blur-3xl"></div>
        </div>

      </div>
    </div>
  );
}